apiVersion: v1
kind: Secret
metadata:
  name: apowerb-secrets
  namespace: apowerb
type: Opaque
stringData:
  DB_NAME: th2agent
  DB_USER: th2agent
  DB_PASSWORD: change-me
  ENCRYPT_KEY: ""
  TEST_TOKEN: ""
