{{- if .Values.otelCollector.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "apowerb.otel.fullname" . }}
  namespace: {{ include "apowerb.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "apowerb.name" . }}
    app.kubernetes.io/component: otel-collector
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "apowerb.name" . }}
    app.kubernetes.io/component: otel-collector
  ports:
    - name: otlp-http
      port: 4318
      targetPort: 4318
      protocol: TCP
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
      protocol: TCP
{{- end }}
