{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: apowerb-secrets
  namespace: {{ include "apowerb.namespace" . }}
type: Opaque
stringData:
  DB_NAME: {{ .Values.postgres.database | quote }}
  DB_USER: {{ .Values.postgres.user | quote }}
  DB_PASSWORD: {{ .Values.postgres.password | quote }}
  ENCRYPT_KEY: {{ .Values.backend.env.encryptKey | quote }}
  TEST_TOKEN: {{ .Values.backend.env.testToken | quote }}
{{- end }}
