apiVersion: v1
kind: Service
metadata:
  name: {{ include "apowerb.backend.fullname" . }}
  namespace: {{ include "apowerb.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "apowerb.name" . }}
    app.kubernetes.io/component: backend
spec:
  selector:
    app.kubernetes.io/name: {{ include "apowerb.name" . }}
    app.kubernetes.io/component: backend
  ports:
    - name: http
      port: {{ .Values.service.backend.port }}
      targetPort: 8000
      protocol: TCP
