#!/usr/bin/env bash
# Writes the `apowerb-secrets` Secret for a kubectl install (k8s/apowerb/).
#
# The Kubernetes counterpart of generate-secrets.sh, without Helm: openssl is
# all it needs. The file it writes holds real credentials -- it is in
# .gitignore, and it is created with mode 600.
#
# It REFUSES to overwrite an existing file, for the same reason
# generate-secrets.sh never replaces a value: a new ENCRYPT_KEY makes every
# integration token already encrypted in the database unreadable, and a new
# DB_PASSWORD no longer matches the one PostgreSQL was initialised with.
#
#   scripts/generate-k8s-secret.sh            # writes k8s/secret.yaml
#   scripts/generate-k8s-secret.sh <file>     # writes <file>

set -euo pipefail

cd "$(dirname "$0")/.."

out="${1:-k8s/secret.yaml}"
namespace="apowerb"

if [ -e "$out" ]; then
    echo "$out already exists: left as is. Delete it yourself only if no" >&2
    echo "installation uses it yet -- its keys are what the database holds." >&2
    exit 1
fi

# Hex: the password also goes inside TH2PULSE_DB_DSN, a URL, where `@`, `/`
# and `:` would have to be percent-encoded.
db_name="th2agent"
db_user="th2agent"
db_password="$(openssl rand -hex 24)"
# A Fernet key: 32 random bytes in url-safe base64.
encrypt_key="$(openssl rand -base64 32 | tr '+/' '-_')"

umask 077
cat > "$out" <<YAML
# Generated by scripts/generate-k8s-secret.sh -- real credentials, keep out of
# version control and back up ENCRYPT_KEY: it cannot be regenerated.
apiVersion: v1
kind: Secret
metadata:
  name: apowerb-secrets
  namespace: ${namespace}
type: Opaque
stringData:
  DB_NAME: "${db_name}"
  DB_USER: "${db_user}"
  DB_PASSWORD: "${db_password}"
  ENCRYPT_KEY: "${encrypt_key}"
  TEST_TOKEN: ""
  TH2ETL_API_KEY: "$(openssl rand -hex 32)"
  TH2PULSE_INGEST_TOKEN: "$(openssl rand -hex 32)"
  TH2PULSE_QUERY_TOKEN: "$(openssl rand -hex 32)"
  TH2PULSE_DB_DSN: "postgresql://${db_user}:${db_password}@apowerb-postgres:5432/${db_name}"
  # Optional keys, read only when present (the Deployments reference them
  # with optional: true). Add the ones you use, never an empty one: an empty
  # variable is read by the core as a choice, not as an absence.
  #   DEFAULT_LLM_API_KEY, DEFAULT_SUPERADMIN_PASSWORD, SMTP_PASSWORD,
  #   MICROSOFT_INTEGRATION_CLIENT_SECRET, GOOGLE_INTEGRATION_CLIENT_SECRET,
  #   S3_ACCESS_KEY, S3_ACCESS_KEY_SECRET, RAG_WEBHOOK_SECRET
YAML
chmod 600 "$out"

echo "Written: $out"
echo "Apply it before the stack:  kubectl apply -f k8s/apowerb/00-namespace.yaml -f $out"
